Chương trình/Source/Source/WebBanHang/Areas/Admin/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using WebBanHang.Helper;
using WebBanHang.Models;

namespace WebBanHang.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SanPhamsController : Controller
    {
        private readonly dbBanHangContext _context;
        public INotyfService _notyfService { get; }

        public SanPhamsController(dbBanHangContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;

        }

        // GET: Admin/SanPhams
        public async Task<IActionResult> Index(int page = 1, int MaLoai = 0)
        {
            var taikhoanID = HttpContext.Session.GetString("AdminId");
            if (string.IsNullOrEmpty(taikhoanID))
            {
                return RedirectToAction("DangNhap", "AccountsAdmin");
            }

            var pageNumber = page;
            var pageSize = 10;

            List<SanPham> lsSanPham = new List<SanPham>();

            //filter op
            if(MaLoai != 0)
            {
                lsSanPham = _context.SanPhams
                .AsNoTracking()
                .Where(x=>x.MaLoai== MaLoai)
                .Include(s => s.MaLoaiNavigation)
                .Include(s => s.MaThNavigation)
                .OrderByDescending(x => x.MaSp).ToList();
            }
            else
            {
                lsSanPham = _context.SanPhams
                .AsNoTracking()
                .Include(s => s.MaLoaiNavigation)
                .Include(s => s.MaThNavigation)
                .OrderByDescending(x => x.MaSp).ToList();
            }

            //page
            PagedList<SanPham> models = new PagedList<SanPham>(lsSanPham.AsQueryable(), pageNumber, pageSize);

            ViewBag.CurrentPage = pageNumber;
            ViewBag.CurrentMaLoai = MaLoai;

            //filter select
            List<SelectListItem> lsQuantityStt = new List<SelectListItem>();
            lsQuantityStt.Add(new SelectListItem() { Text = "Còn hàng", Value = "1" });
            lsQuantityStt.Add(new SelectListItem() { Text = "Hết hàng", Value = "0" });
            ViewData["lsQuantityStt"] = lsQuantityStt;

            //lấy slted value
            ViewData["LoaiSP"] = new SelectList(_context.LoaiSanPhams, "MaLoai", "TenLoai", MaLoai);
            ViewData["ThuongHieu"] = new SelectList(_context.ThuongHieus, "MaTh", "TenTh");

            return View(models);
        }

        //
        // Filter(int maLoai=0, int maTh=0, int stt=-1)
        public IActionResult Filter(int MaLoai = 0, int Stt=-1)
        {
            var url = $"/Admin/SanPhams?MaLoai={MaLoai}";
            if (MaLoai == 0)
            {
                url = $"/Admin/SanPhams";
            }
            else
            {
                //if(maLoai==0) url = $"/Admin/SanPhams?maTh={maTh}&stt={stt}";
            }
            return Json(new { status = "success", RedirectUrl = url });
        }

        // GET: Admin/SanPhams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams
                .Include(s => s.MaLoaiNavigation)
                .Include(s => s.MaThNavigation)
                .FirstOrDefaultAsync(m => m.MaSp == id);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

        // GET: Admin/SanPhams/Create
        public IActionResult Create()
        {
            ViewData["LoaiSP"] = new SelectList(_context.LoaiSanPhams, "MaLoai", "TenLoai");
            ViewData["ThuongHieu"] = new SelectList(_context.ThuongHieus, "MaTh", "TenTh");
            return View();
        }

        // POST: Admin/SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaSp,TenSp,GiaBan,GiaGiam,SoLuongCo,Anh,CongSuat,KhoiLuong,MoTa,BaoHanh,MaLoai,MaTh")] SanPham sanPham, Microsoft.AspNetCore.Http.IFormFile fAnh)
        {
            if (ModelState.IsValid)
            {
                if(sanPham.GiaGiam >= sanPham.GiaBan)
                {
                    _notyfService.Warning("Giá giảm phải nhỏ hơn giá bán");
                    return View(sanPham);
                }
                sanPham.TenSp = Utilities.ToTitleCase(sanPham.TenSp);
                if(fAnh != null)
                {
                    string extension = Path.GetExtension(fAnh.FileName);
                    string img = Utilities.SEOUrl(sanPham.TenSp)+"-"+ Utilities.RandomGuid() + extension;
                    sanPham.Anh = await Utilities.UploadFile(fAnh, @"sanpham", img.ToLower());
                }
                if (string.IsNullOrEmpty(sanPham.TenSp)) sanPham.Anh = "default.jpg";

                _context.Add(sanPham);
                await _context.SaveChangesAsync();
                _notyfService.Success("Tạo mới thành công");
                return RedirectToAction(nameof(Index));
            }
            ViewData["LoaiSP"] = new SelectList(_context.LoaiSanPhams, "MaLoai", "TenLoai", sanPham.MaLoai);
            ViewData["ThuongHieu"] = new SelectList(_context.ThuongHieus, "MaTh", "TenTh", sanPham.MaTh);
            return View(sanPham);
        }

        // GET: Admin/SanPhams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams.FindAsync(id);
            if (sanPham == null)
            {
                return NotFound();
            }
            ViewData["LoaiSP"] = new SelectList(_context.LoaiSanPhams, "MaLoai", "TenLoai", sanPham.MaLoai);
            ViewData["ThuongHieu"] = new SelectList(_context.ThuongHieus, "MaTh", "TenTh", sanPham.MaTh);
            return View(sanPham);
        }

        // POST: Admin/SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaSp,TenSp,GiaBan,GiaGiam,SoLuongCo,Anh,CongSuat,KhoiLuong,MoTa,BaoHanh,MaLoai,MaTh")] SanPham sanPham, Microsoft.AspNetCore.Http.IFormFile fAnh)
        {
            if (id != sanPham.MaSp)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    sanPham.TenSp = Utilities.ToTitleCase(sanPham.TenSp);
                    if (fAnh != null)
                    {
                        string extension = Path.GetExtension(fAnh.FileName);
                        string img = Utilities.SEOUrl(sanPham.TenSp) + extension;
                        sanPham.Anh = await Utilities.UploadFile(fAnh, @"sanpham", img.ToLower());
                    }
                    if (string.IsNullOrEmpty(sanPham.TenSp)) sanPham.Anh = "default.jpg";

                    _context.Update(sanPham);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Cập nhật thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SanPhamExists(sanPham.MaSp))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["LoaiSP"] = new SelectList(_context.LoaiSanPhams, "MaLoai", "TenLoai", sanPham.MaLoai);
            ViewData["ThuongHieu"] = new SelectList(_context.ThuongHieus, "MaTh", "TenTh", sanPham.MaTh);
            return View(sanPham);
        }

        // GET: Admin/SanPhams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPhams
                .Include(s => s.MaLoaiNavigation)
                .Include(s => s.MaThNavigation)
                .FirstOrDefaultAsync(m => m.MaSp == id);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

        // POST: Admin/SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var sanPham = await _context.SanPhams.FindAsync(id);
                _context.SanPhams.Remove(sanPham);
                await _context.SaveChangesAsync();
                _notyfService.Success("Xóa thành công");
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                _notyfService.Warning("Xóa thất bại");
                return RedirectToAction(nameof(Index));
            }
            
        }

        private bool SanPhamExists(int id)
        {
            return _context.SanPhams.Any(e => e.MaSp == id);
        }
    }
}

Chương trình/Source/Source/WebBanHang/Controllers/SanPhamController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using System;
using System.Linq;
using System.Threading.Tasks;
using WebBanHang.Models;

namespace WebBanHang.Controllers
{
    public class SanPhamController : Controller
    {
        private readonly dbBanHangContext _context;
        public INotyfService _notyfService { get; }
        public SanPhamController(dbBanHangContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        [Route("sanpham")]
        public IActionResult Index(int? page, string? searchKey, int? sort)
        {
            try
            {
                var pageNumber = page == null || page <= 0 ? 1 : page.Value;
                var pageSize = 9;

                var lsSanPham = _context.SanPhams
                    .AsNoTracking()
                    .Include(s => s.MaLoaiNavigation)
                    .Include(s => s.MaThNavigation)
                    .OrderByDescending(x => x.MaSp).ToList();

                if (searchKey != null)
                {
                    lsSanPham = lsSanPham.Where(x=>x.TenSp.ToLower().Contains(searchKey.ToLower())).ToList();
                }
                if(sort!= null)
                {
                    if (sort == 1)
                    {
                        lsSanPham = lsSanPham.OrderBy(x => x.GiaGiam).ToList();
                    }
                    else if(sort==2)
                    {
                        lsSanPham = lsSanPham.OrderByDescending(x => x.GiaGiam).ToList();
                    }
                }

                PagedList<SanPham> models = new PagedList<SanPham>(lsSanPham.AsQueryable(), pageNumber, pageSize);
                ViewBag.CurrentPage = pageNumber;

                //
                var dmsp = _context.LoaiSanPhams
                    .AsNoTracking()
                    .OrderBy(x => x.MaLoai).ToList();
                ViewBag.DMSP = dmsp;
                //
                var spmoi = _context.SanPhams
                    .AsNoTracking()
                    .Include(s => s.MaLoaiNavigation)
                    .Include(s => s.MaThNavigation)
                    .OrderByDescending(x => x.MaSp)
                    .Take(3)
                    .ToList();
                ViewBag.SPM = spmoi;
                //
                return View(models);
            }
            catch
            {
                return RedirectToAction("Index", "Home");
            }
            
        }

        [Route("sanpham/sort")]
        public IActionResult Sort(int sort)
        {
            var url = $"/sanpham?sort={sort}";
            if (sort == 0)
            {
                url = $"/sanpham";
            }
            else
            {
                //if(maLoai==0) url = $"/Admin/SanPhams?maTh={maTh}&stt={stt}";
            }
            return Json(new { status = "success", RedirectUrl = url });
        }

        [Route("sanphams/{MaLoai}")]
        public IActionResult List(int MaLoai, int page = 1)
        {
            try
            {
                //
                var dmsp = _context.LoaiSanPhams
                    .AsNoTracking()
                    .OrderBy(x => x.MaLoai).ToList();
                ViewBag.DMSP = dmsp;
                //

                var pageNumber = page;
                var pageSize = 9;
                var danhmuc = _context.LoaiSanPhams
                    .AsNoTracking()
                    .SingleOrDefault(x => x.MaLoai == MaLoai);

                var lsSanPham = _context.SanPhams
                    .AsNoTracking()
                    .Where(x => x.MaLoai == MaLoai)
                    .Include(s => s.MaLoaiNavigation)
                    .Include(s => s.MaThNavigation)
                    .OrderByDescending(x => x.MaSp).ToList();

                PagedList<SanPham> models = new PagedList<SanPham>(lsSanPham.AsQueryable(), pageNumber, pageSize);
                ViewBag.CurrentPage = pageNumber;
                ViewBag.CurrentLoaiSP = danhmuc;

                return View(models);
            }
            catch
            {
                return RedirectToAction("Index", "Home");
            }

        }
        [Route("sanpham/{id}")]
        public IActionResult Detail(int id)
        {
            try
            {
                var product = _context.SanPhams
                .Include(x => x.MaLoaiNavigation)
                .Include(x => x.MaThNavigation)
                .FirstOrDefault(x => x.MaSp == id);

                if (product == null)
                {
                    return RedirectToAction("Index");
                }

                var lsProduct = _context.SanPhams
                    .AsNoTracking()
                    .Where(x=>x.MaLoai==product.MaLoai &&x.MaSp!=id)
                    .Take(4)
                    .OrderByDescending(x=>x.MaSp)
                    .ToList();
                ViewBag.SanPham = lsProduct;

                var lsDG =_context.DanhGiaSanPhams
                    .Include(x=>x.MaKhNavigation)
                    .AsNoTracking()
                    .Where(x=>x.MaSp==id)
                    .OrderByDescending(x=>x.MaDg)
                    .Take(5)
                    .ToList();
                ViewBag.DanhGia = lsDG;

                return View(product);
            }
            catch
            {
                return RedirectToAction("Index", "Home");

            }

        }

        [HttpPost]
        [Route("sanpham/danhgia")]
        public async Task<IActionResult> DanhGia(int? id, byte diem, string noiDung)
        {
            if (id == null)
            {
                return RedirectToAction("Index", "SanPham");
            }
            try
            {
                var taikhoanID = HttpContext.Session.GetString("CustomerId");
                if (string.IsNullOrEmpty(taikhoanID))
                {
                    return RedirectToAction("DangNhap", "Accounts");
                }
                var khachhang = _context.KhachHangs.AsNoTracking()
                    .SingleOrDefault(x => x.MaKh == Convert.ToInt32(taikhoanID));
                if (khachhang == null)
                {
                    return NotFound();
                }
                //
                
                //
                DanhGiaSanPham dgsp = new DanhGiaSanPham();
                dgsp.MaKh = khachhang.MaKh;
                dgsp.MaSp = id;
                dgsp.Diem = diem;
                dgsp.NoiDung = noiDung;
                dgsp.ThoiGian = DateTime.Now;

                _context.Add(dgsp);
                _context.SaveChanges();

                _notyfService.Success("Đánh giá thành công");

                return RedirectToAction("Detail", "SanPham", new { id = id });

            }
            catch
            {
                return RedirectToAction("Index", "SanPham", new { id = id });
            }

        }

    }
}

Chương trình/Source/Source/WebBanHang/Areas/Admin/Views/SanPhams/Create.cshtml
@model WebBanHang.Models.SanPham

@{
    ViewData["Title"] = "Thêm mới";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
    <h2 class="header-title">Quản lý sản phẩm</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="SanPhams" asp-action="Index" class="breadcrumb-item">Sản phẩm</a>
            <span class="breadcrumb-item active">Thêm sản phẩm</span>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Tạo mới sản phẩm</h4>
        <form asp-controller="SanPhams" asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Tên</label>
                <div class="col-sm-6">
                    <input type="text" class="form-control" asp-for="TenSp" placeholder="Tên sản phẩm">
                    <span asp-validation-for="TenSp" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Giá bán</label>
                <div class="col-sm-2">
                    <input type="text" class="form-control" asp-for="GiaBan" placeholder="Giá bán">
                    <span asp-validation-for="GiaBan" class="text-danger"></span>
                </div>

                <label class="col-sm-1 offset-sm-1 col-form-label">Giá giảm</label>
                <div class="col-sm-2">
                    <input type="text" class="form-control" asp-for="GiaGiam" placeholder="Giá giảm">
                    <span asp-validation-for="GiaGiam" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Số lượng</label>
                <div class="col-sm-2">
                    <input type="text" class="form-control" asp-for="SoLuongCo" placeholder="Số lượng">
                    <span asp-validation-for="SoLuongCo" class="text-danger"></span>
                </div>
            </div>
            @*Ảnh*@
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Ảnh</label>
                <div class="col-sm-4">
                    <input type="file" id="fAnh" name="fAnh" class="form-control" asp-for="Anh">
                    @*<span asp-validation-for="Anh" class="text-danger"></span>*@
                </div>

            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label"></label>
                <div class="col-sm-1">
                    <div class="d-flex align-items-center">
                        <img id="image_upload_preview" class="img-fluid img-thumbnail" src="~/images/sanpham/default.jpg" style="max-width:100px" alt="img">
                    </div>
                </div>
            </div>
            @*Ảnh*@
            @* <div class="form-group row">
                <label class="col-sm-2 col-form-label">Công suất (W)</label>
                <div class="col-sm-2">
                    <input type="text" class="form-control" asp-for="CongSuat" placeholder="Công suất">
                    <span asp-validation-for="CongSuat" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Khối lượng (Kg)</label>
                <div class="col-sm-2">
                    <input type="text" class="form-control" asp-for="KhoiLuong" placeholder="Khối lượng">
                    <span asp-validation-for="KhoiLuong" class="text-danger"></span>
                </div>
            </div> *@
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Bảo hành (tháng)</label>
                <div class="col-sm-2">
                    <input type="text" class="form-control" asp-for="BaoHanh" placeholder="Bảo hành">
                    <span asp-validation-for="BaoHanh" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Mô tả</label>
                <div class="col-sm-6">
                    <textarea rows="7" class="form-control" asp-for="MoTa" placeholder="Mô tả"></textarea>
                    <span asp-validation-for="MoTa" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Loại sản phẩm</label>
                <div class="col-sm-3">
                    <select class="custom-select" asp-for="MaLoai" asp-items="ViewBag.LoaiSP">
                        <option value="" disabled selected>-Chọn loại sp-</option>
                    </select>
                    <span asp-validation-for="MaLoai" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Thương hiệu</label>
                <div class="col-sm-3">
                    <select class="custom-select" asp-for="MaTh" asp-items="ViewBag.ThuongHieu">
                        <option value="" disabled selected>-Chọn thương hiệu-</option>
                    </select>
                    <span asp-validation-for="MaTh" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-5">
                    <button type="submit" class="btn btn-primary">Thêm</button>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts{
    <script>
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#image_upload_preview').attr('src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#fAnh").change(function () {
            readURL(this);
        });

    </script>
}

Chương trình/Source/Source/WebBanHang/Areas/Admin/Views/SanPhams/Delete.cshtml
@model WebBanHang.Models.SanPham

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
    <h2 class="header-title">Quản lý sản phẩm</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="SanPhams" asp-action="Index" class="breadcrumb-item">Sản phẩm</a>
            <span class="breadcrumb-item active">Xóa sản phẩm</span>
        </nav>
    </div>
</div>

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Xóa sản phẩm</h4>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">ID</label>
            <div class="col-sm-2">
                <input style="background-color:#F7F9F9;" type="text" readonly class="form-control" asp-for="MaSp">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Tên</label>
            <div class="col-sm-6">
                <input style="background-color:#F7F9F9;" type="text" readonly class="form-control" asp-for="TenSp">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Giá bán</label>
            <div class="col-sm-2">
                <input style="background-color:#F7F9F9;" type="text" readonly class="form-control" asp-for="GiaBan">
            </div>

            <label class="col-sm-1 offset-sm-1 col-form-label">Giá giảm</label>
            <div class="col-sm-2">
                <input style="background-color:#F7F9F9;" type="text" readonly class="form-control" asp-for="GiaGiam">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Số lượng</label>
            <div class="col-sm-2">
                <input style="background-color:#F7F9F9;" type="text" readonly class="form-control" asp-for="SoLuongCo">
            </div>
        </div>
        @*Ảnh*@
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Ảnh</label>
            <div class="col-sm-2">
                <div class="d-flex align-items-center">
                    <img class="img-fluid img-thumbnail" src="~/images/sanpham/@Model.Anh" style="max-width: 200px" alt="img">
                </div>
            </div>
        </div>
        @*Ảnh*@
       @*  <div class="form-group row">
            <label class="col-sm-2 col-form-label">Công suất (W)</label>
            <div class="col-sm-2">
                <input style="background-color:#F7F9F9;" type="text" readonly class="form-control" asp-for="CongSuat">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Khối lượng (Kg)</label>
            <div class="col-sm-2">
                <input style="background-color:#F7F9F9;" type="text" readonly class="form-control" asp-for="KhoiLuong">
            </div>
        </div> *@
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Bảo hành (tháng)</label>
            <div class="col-sm-2">
                <input style="background-color:#F7F9F9;" type="text" readonly class="form-control" asp-for="BaoHanh">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Mô tả</label>
            <div class="col-sm-6">
                <textarea style="background-color:#F7F9F9;" readonly rows="7" class="form-control" asp-for="MoTa"></textarea>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Loại sản phẩm</label>
            <div class="col-sm-3">
                <input style="background-color:#F7F9F9;" type="text" readonly class="form-control" asp-for="MaLoaiNavigation.TenLoai">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Thương hiệu</label>
            <div class="col-sm-3">
                <input style="background-color:#F7F9F9;" type="text" readonly class="form-control" asp-for="MaThNavigation.TenTh">
            </div>
        </div>
        <hr/>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Bạn có chắc muốn xóa?</label>
            <div class="col-sm-3">
                <form asp-controller="SanPhams" asp-action="Delete" asp-route-id="@Model.MaSp">
                    <input type="hidden" asp-for="MaSp" />
                    <input type="submit" value="Xác nhận xóa" class="btn btn-danger" />
                </form>
            </div>
        </div>
    </div>
</div>