Chương trình/Source/Source/WebBanHang/Models/LoaiSanPham.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace WebBanHang.Models
{
    public partial class LoaiSanPham
    {
        public LoaiSanPham()
        {
            SanPhams = new HashSet<SanPham>();
        }

        public int MaLoai { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên")]
        public string TenLoai { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập mô tả")]
        public string MoTa { get; set; }

        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}

Chương trình/Source/Source/WebBanHang/Areas/Admin/Controllers/LoaiSanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebBanHang.Models;

namespace WebBanHang.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class LoaiSanPhamsController : Controller
    {
        private readonly dbBanHangContext _context;
        public INotyfService _notyfService { get;}

        public LoaiSanPhamsController(dbBanHangContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService =notyfService;
        }

        // GET: Admin/LoaiSanPhams
        public async Task<IActionResult> Index()
        {
            var taikhoanID = HttpContext.Session.GetString("AdminId");
            if (string.IsNullOrEmpty(taikhoanID))
            {
                return RedirectToAction("DangNhap", "AccountsAdmin");
            }
            return View(await _context.LoaiSanPhams.ToListAsync());
        }

        // GET: Admin/LoaiSanPhams/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loaiSanPham = await _context.LoaiSanPhams
                .FirstOrDefaultAsync(m => m.MaLoai == id);
            if (loaiSanPham == null)
            {
                return NotFound();
            }

            return View(loaiSanPham);
        }

        // GET: Admin/LoaiSanPhams/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/LoaiSanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MaLoai,TenLoai,MoTa")] LoaiSanPham loaiSanPham)
        {
            if (ModelState.IsValid)
            {
                _context.Add(loaiSanPham);
                await _context.SaveChangesAsync();
                _notyfService.Success("Tạo mới thành công");
                return RedirectToAction(nameof(Index));
            }
            return View(loaiSanPham);
        }

        // GET: Admin/LoaiSanPhams/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loaiSanPham = await _context.LoaiSanPhams.FindAsync(id);
            if (loaiSanPham == null)
            {
                return NotFound();
            }
            return View(loaiSanPham);
        }

        // POST: Admin/LoaiSanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MaLoai,TenLoai,MoTa")] LoaiSanPham loaiSanPham)
        {
            if (id != loaiSanPham.MaLoai)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(loaiSanPham);
                    await _context.SaveChangesAsync();
                    _notyfService.Success("Cập nhật thành công");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LoaiSanPhamExists(loaiSanPham.MaLoai))
                    {
                        _notyfService.Warning("Có lỗi xảy ra");
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(loaiSanPham);
        }

        // GET: Admin/LoaiSanPhams/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var loaiSanPham = await _context.LoaiSanPhams
                .FirstOrDefaultAsync(m => m.MaLoai == id);
            if (loaiSanPham == null)
            {
                return NotFound();
            }

            return View(loaiSanPham);
        }

        // POST: Admin/LoaiSanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var loaiSanPham = await _context.LoaiSanPhams.FindAsync(id);
                _context.LoaiSanPhams.Remove(loaiSanPham);
                await _context.SaveChangesAsync();
                _notyfService.Success("Xóa thành công");
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                _notyfService.Warning("Xóa thất bại");
                return RedirectToAction(nameof(Index));
            }
            
        }

        private bool LoaiSanPhamExists(int id)
        {
            return _context.LoaiSanPhams.Any(e => e.MaLoai == id);
        }
    }
}

Chương trình/Source/Source/WebBanHang/Areas/Admin/Views/LoaiSanPhams/Create.cshtml
@model WebBanHang.Models.LoaiSanPham

@{
    ViewData["Title"] = "Tạo mới loại sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <h2 class="header-title">Quản lý loại sản phẩm</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="LoaiSanPhams" asp-action="Index" class="breadcrumb-item">Loại sản phẩm</a>
            <span class="breadcrumb-item active">Tạo mới loại sản phẩm</span>
        </nav>
    </div>
</div>


<div class="card">
    <div class="card-body">
        <h4 class="card-title">Tạo mới loại sản phẩm</h4>
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Tên</label>
                <div class="col-sm-5">
                    <input type="text" class="form-control" asp-for="TenLoai" placeholder="Tên">
                    <span asp-validation-for="TenLoai" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Mô tả</label>
                <div class="col-sm-5">
                    <textarea rows="5" class="form-control" asp-for="MoTa" placeholder="Mô tả"></textarea>
                    <span asp-validation-for="MoTa" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-5">
                    <button type="submit" class="btn btn-primary">Thêm</button>
                </div>
            </div>
        </form>
    </div>
</div>

Chương trình/Source/Source/WebBanHang/Areas/Admin/Views/LoaiSanPhams/Delete.cshtml
@model WebBanHang.Models.LoaiSanPham

@{
    ViewData["Title"] = "Xóa loại sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <h2 class="header-title">Quản lý loại sản phẩm</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="LoaiSanPhams" asp-action="Index" class="breadcrumb-item">Loại sản phẩm</a>
            <span class="breadcrumb-item active">Xóa loại sản phẩm</span>
        </nav>
    </div>
</div>


<div class="card">
    <div class="card-body">
        <h4 class="card-title">Xóa loại sản phẩm</h4>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">ID</label>
            <div class="col-sm-2">
                <input style="background-color:#F7F9F9;" type="text" readonly class="form-control" asp-for="MaLoai" placeholder="ID">
            </div>
        </div>

        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Tên </label>
            <div class="col-sm-5">
                <input style="background-color:#F7F9F9;" type="text" class="form-control" readonly asp-for="TenLoai" placeholder="Tên">
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Mô tả</label>
            <div class="col-sm-5">
                <textarea style="background-color:#F7F9F9;" rows="5" class="form-control" readonly asp-for="MoTa" placeholder="Mô tả"></textarea>
            </div>
        </div>
        <div class="form-group row">
            <label class="col-sm-2 col-form-label">Bạn có chắc muốn xóa?</label>
            <div class="col-sm-3">
                <form asp-area="Admin" asp-action="Delete" asp-route-id="@Model.MaLoai">
                    <input type="hidden" asp-for="MaLoai" />
                    <input type="submit" value="Xác nhận xóa" class="btn btn-danger" />
                </form>
            </div>
        </div>
    </div>
</div>

Chương trình/Source/Source/WebBanHang/Areas/Admin/Views/LoaiSanPhams/Details.cshtml
@model WebBanHang.Models.LoaiSanPham

@{
    ViewData["Title"] = "Thông tin loại sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <h2 class="header-title">Quản lý loại sản phẩm</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="LoaiSanPhams" asp-action="Index" class="breadcrumb-item">Loại sản phẩm</a>
            <span class="breadcrumb-item active">Thông tin loại sản phẩm</span>
        </nav>
    </div>
</div>
<hr />

<div class="card">
    <div class="card-body">
        <h4 class="card-title">Thông tin loại sản phẩm</h4>
        <div class="table-responsive">
            <table class="product-info-table m-t-20">
                <tbody>
                    <tr>
                        <td>ID:</td>
                        <td class="text-dark font-weight-semibold">@Model.MaLoai</td>
                    </tr>
                    <tr>
                        <td>Tên:</td>
                        <td>@Model.TenLoai</td>
                    </tr>
                    <tr>
                        <td>Mô tả:</td>
                        <td>@Model.MoTa</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

Chương trình/Source/Source/WebBanHang/Areas/Admin/Views/LoaiSanPhams/Edit.cshtml
@model WebBanHang.Models.LoaiSanPham

@{
    ViewData["Title"] = "Chỉnh sửa loại sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <h2 class="header-title">Quản lý loại sản phẩm</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <a asp-area="Admin" asp-controller="LoaiSanPhams" asp-action="Index" class="breadcrumb-item">Loại sản phẩm</a>
            <span class="breadcrumb-item active">Chỉnh sửa loại sản phẩm</span>
        </nav>
    </div>
</div>


<div class="card">
    <div class="card-body">
        <h4 class="card-title">Sửa loại sản phẩm</h4>
        <form asp-action="Edit" asp-route-id="@Model.MaLoai" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaLoai" />

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">ID</label>
                <div class="col-sm-2">
                    <input style="background-color:#F7F9F9;" type="text" readonly class="form-control" asp-for="MaLoai" placeholder="ID">
                </div>
            </div>

            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Tên </label>
                <div class="col-sm-5">
                    <input type="text" class="form-control" asp-for="TenLoai" placeholder="Tên">
                    <span asp-validation-for="TenLoai" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label">Mô tả</label>
                <div class="col-sm-5">
                    <textarea rows="5" class="form-control" asp-for="MoTa" placeholder="Mô tả"></textarea>
                    <span asp-validation-for="MoTa" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-5">
                    <button type="submit" class="btn btn-primary">Lưu thay đổi</button>
                </div>
            </div>
        </form>
    </div>
</div>

Chương trình/Source/Source/WebBanHang/Areas/Admin/Views/LoaiSanPhams/Index.cshtml
@model IEnumerable<WebBanHang.Models.LoaiSanPham>

@{
    ViewData["Title"] = "Quản lý loại sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <h2 class="header-title">Quản lý loại sản phẩm</h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
            <span class="breadcrumb-item active">Loại sản phẩm</span>
        </nav>
    </div>
</div>


<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-4">
                <a class="btn btn-primary" asp-area="Admin" asp-controller="LoaiSanPhams" asp-action="Create">
                    <i class="anticon anticon-plus-circle m-r-5"></i>
                    <span>Thêm mới</span>
                </a>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-hover e-commerce-table">
                <thead>
                    <tr>
                        <th style="font-weight:bold">ID</th>
                        <th style="font-weight:bold">Tên</th>
                        <th style="font-weight:bold">Mô tả</th>
                        <th style="font-weight:bold">#</th>
                    </tr>
                </thead>
                <tbody id="records_table">
                    @if (Model != null)
                    {
                        foreach (var item in Model)
                        {
                            <tr>
                                <td style="font-weight:bold">@item.MaLoai</td>
                                <td>@item.TenLoai</td>
                                <td>@item.MoTa</td>
                                <td>
                                    <a class="btn btn-icon btn-hover btn-sm btn-rounded" asp-area="Admin" asp-controller="LoaiSanPhams" asp-action="Edit" asp-route-id="@item.MaLoai">
                                        <i class="anticon anticon-edit"></i>
                                    </a>
                                    <a class="btn btn-icon btn-hover btn-sm btn-rounded" asp-area="Admin" asp-controller="LoaiSanPhams" asp-action="Delete" asp-route-id="@item.MaLoai">
                                        <i class="anticon anticon-delete"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>